name: Deploy to Endora (IceCreamReact)

on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (Vite)
        run: npm run build
        # vite.config.js musí mít: base: '/DogsShelterReact/'

      - name: Check if dist exists
        id: check
        run: |
          if [ -d "dist" ]; then
            echo "has_dist=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_dist=false" >> "$GITHUB_OUTPUT"
          fi

      # === Deploy, varianta A: dist existuje ===
      - name: Deploy via FTPS (upload dist contents)
        if: steps.check.outputs.has_dist == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          passive: true
          server-dir: ${{ secrets.FTP_DIR }}IceCreamReact/
          local-dir: ./dist/
          dangerous-clean-slate: true
          exclude: |
            **/.DS_Store

      # === Deploy, varianta B: dist NEexistuje → čistý wipe cílové složky ===
      - name: Deploy empty (wipe remote)
        if: steps.check.outputs.has_dist != 'true'
        run: mkdir -p empty
      - name: Wipe remote dir via FTPS
        if: steps.check.outputs.has_dist != 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          passive: true
          server-dir: ${{ secrets.FTP_DIR }}DogsShelterReact/
          local-dir: ./empty/
          dangerous-clean-slate: true
